# Generated by Django 4.1.3 on 2022-11-09 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_stud_branch_remove_stud_parents_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='s_name',
        ),
        migrations.AddField(
            model_name='stud',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stud',
            name='roll_no',
            field=models.CharField(max_length=30),
        ),
    ]
