# Generated by Django 4.1.3 on 2022-11-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_stud_s_name_stud_name_alter_stud_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='parent_name',
            new_name='parentName',
        ),
        migrations.RenameField(
            model_name='stud',
            old_name='roll_no',
            new_name='rollNo',
        ),
    ]
