# Generated by Django 4.1.3 on 2022-11-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_parent_name_stud_parentname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='parentName',
            new_name='parent_Name',
        ),
        migrations.RenameField(
            model_name='stud',
            old_name='rollNo',
            new_name='roll',
        ),
    ]
