# Generated by Django 4.1.3 on 2022-11-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_parentname_stud_parent_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='parent_Name',
            new_name='parentName',
        ),
    ]
