# Generated by Django 4.1.3 on 2022-11-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_parent_name_stud_parentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=10)),
                ('subject1', models.CharField(max_length=10)),
                ('maxMarkSub1', models.IntegerField()),
                ('markObSub1', models.IntegerField()),
                ('subject2', models.CharField(max_length=10)),
                ('maxMarkSub2', models.IntegerField()),
                ('markObSub2', models.IntegerField()),
                ('subject3', models.CharField(max_length=10)),
                ('maxMarkSub3', models.IntegerField()),
                ('markObSub3', models.IntegerField()),
                ('subject4', models.CharField(max_length=10)),
                ('maxMarkSub4', models.IntegerField()),
                ('markObSub4', models.IntegerField()),
                ('subject5', models.CharField(max_length=10)),
                ('maxMarkSub5', models.IntegerField()),
                ('markObSub5', models.IntegerField()),
                ('subject6', models.CharField(max_length=10)),
                ('maxMarkSub6', models.IntegerField()),
                ('markObSub6', models.IntegerField()),
            ],
            options={
                'db_table': 'Stud_marks',
            },
        ),
        migrations.AlterField(
            model_name='stud',
            name='roll',
            field=models.CharField(max_length=10),
        ),
    ]
